# Generated by Django 5.2.1 on 2025-08-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('score', models.FloatField()),
                ('email_sent', models.BooleanField(default=False)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.jobdescription')),
            ],
        ),
    ]
